config/routes.rb
Rails.application.routes.draw do
  root to: "games#new"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :games, only: [:show, :index, :new, :create] do
    resources :players, only: [:show, :index, :update, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/building.rb
class Building < ApplicationRecord
  belongs_to :player
  # disable STI
  self.inheritance_column = :_type_disabled
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :players
  accepts_nested_attributes_for :players
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :buildings
  belongs_to :game
  after_create_commit { broadcast_append_to('players') }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def new
    @games = Game.all
    @game = Game.new
    4.times { @game.players.build }
  end

  def create
    @game = Game.new(game_params)
    @players = decide_turn(@game)
    if @game.save
      redirect_to game_path(@game)
    end
  end

  def show
    @game = Game.find(params[:id])
    @players = @game.players.sort_by{ |k| k[:turn] }
    @buildings = Building.all
  end

  def gamerun(player, dicenumber)
    #Players take turns to roll the dice
    newGame.move(dicenumber, player)
    newGame.pay_rent(player)
    # Show the result of this turn
    newGame.status(dicenumber, player)
    sleep(0.5)
    # Check the player is alive or not
    if newGame.check_is_alive?(player) == false
    end
  end

  def decide_turn(game)
    myArray = [1, 2, 3, 4]
    selected = []
    selected << myArray.sample
    selected << (myArray - selected).sample
    selected << (myArray - selected).sample
    selected << (myArray - selected).sample
    players = game.players.to_a
    for i in 0..3
      players[i].turn = selected[i]
    end
    players.each{ |p| p.save!}
    return players.sort! {|x, y| x["turn"] <=> y["turn"]}
  end



  private
  def game_params
    params.require(:game).permit(:id, players_attributes: [:id, :name, :money, :position, :is_alive, :game_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def update
    @game = Game.find(params[:game_id])
    @players = @game.players.sort_by{ |k| k[:turn] }
  end

  private
  def player_params
    params.require(:player).permit(:id, :name, :money, :position, :is_alive, :turn, :game_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/_dice.html.erb
<div id="dice" data-controller="dice" class="p-3" style="width: 60px;">
<%# <button type="button" class="btn m-2" id="rollbutton">roll the dice</button> %>
  <div data-dice-target="diceface">
    <div class="dice first-face" style="display: inline-flex">
      <span class="dot">
      </span>
    </div>

    <div class="dice second-face" style="display: none">
      <span class="dot">
      </span>
      <span class="dot">
      </span>
    </div>

    <div class="dice third-face" style="display: none">
      <span class="dot"></span>
      <span class="dot"></span>
      <span class="dot"></span>
    </div>

    <div class="fourth-face dice" style="display: none">
      <div class="column">
          <span class="dot"></span>
          <span class="dot"></span>
      </div>
      <div class="column">
          <span class="dot"></span>
          <span class="dot"></span>
      </div>
    </div>

    <div class="fifth-face dice" style="display: none">
      <div class="column">
          <span class="dot"></span>
          <span class="dot"></span>
      </div>
      <div class="column">
          <span class="dot"></span>
      </div>
      <div class="column">
          <span class="dot"></span>
          <span class="dot"></span>
      </div>
    </div>

    <div class="sixth-face dice" style="display: none">
      <div class="column">
          <span class="dot"></span>
          <span class="dot"></span>
          <span class="dot"></span>
      </div>
      <div class="column">
          <span class="dot"></span>
          <span class="dot"></span>
          <span class="dot"></span>
      </div>
    </div>
  </div>
</div>

app/views/games/_result.html.erb
<%= turbo_stream_from @game, :players%>
<div id="players">
  <%= render @game.players %>
</div>
<div data-controller="dice" class="py-5">
  <div class="text-center">
    <button type="button" data-action="click->dice#nextPlayer" class="btn btn-primary">Next Round</button>
  </div>
  <div class="d-flex justify-content-between">
    <div class="p-3 align-middle">
        Current Player is: <span id ="cur_player_name"></span><br>
        Current Position is: <span id ="cur_player_position"></span><br>
        Next Position is: <span id ="next_position"></span><br>
        The dice number is: <span class="p-3" id="dicenumber"></span><br>
    </div>
    <div class="justify-content-center">
        <%= render "dice" %>
    </div>
  </div>
</div>

app/views/games/new.html.erb
<h1>Welcome to Monopoly Game</h1>

<p>wanna start a new game?</p>

<%= form_with model: @game do |form| %>
  Players:
  <ul>
    <%= form.fields_for :players do |player| %>
      <li>
        <%= player.label :name %>
         <%= player.text_field :name %>
      </li>
    <% end %>
    <%= form.submit %>
  </ul>
<% end %>

<%# <button>see a demo game 01</button>
<button>see a demo game 02</button> %>

app/views/games/show.html.erb
<div class="container">
  <div class="text-center p-3">
    <h2>Welcome to Monopoly Game</h2>
    <%= link_to "new game", new_game_path %>
  </div>
  <div class="d-flex justify-content-center">
    <div class='p-3'>
      <%= render 'result' %>
    </div>
    <div style="width:140px"></div>
    <div class="main" data-controller='table'>
      <div class="circle" id='cell0' data-index='0'>
        <div class="row row-cols-2">
          <div class="col d-flex align-items-start"><div class="player player1 active"></div></div>
          <div class="col d-flex align-items-start justify-content-end"><div class="player player2 active"></div></div>
          <div class="col d-flex align-items-end"><div class="player player3 active"></div></div>
          <div class="col d-flex align-items-end justify-content-end"><div class="player player4 active"></div></div>
        </div>
      </div>
      <div class="circle" id='cell1' data-index='1'></div>
      <div class="circle" id='cell2' data-index='2'></div>
      <div class="circle" id='cell3' data-index='3'></div>
      <div class="circle" id='cell4' data-index='4'></div>
      <div class="circle" id='cell5' data-index='5'></div>
      <div class="circle" id='cell6' data-index='6'></div>
      <div class="circle" id='cell7' data-index='7'></div>
      <div class="circle" id='cell8' data-index='8'></div>
    </div>
  </div>
</div>

<div class="d-none buildings_class">
  <% @buildings.each do |b| %>
  <li><%= b.name %></li>
  <% end %>
</div>
<%= content_tag :div, class: "players_class", data: {players: @players} do %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Game02</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/players/_player.html.erb
<div id ="<%= dom_id(player) %>">
Player: <%= player.name %> | Money: $<%= player.money %> | Order: <%= player.turn %>
</div>

app/views/players/_update.html.erb
<ul>
<li><%= image_tag('icons8-insect-64.png', size: '40')%> <%= render "players/player", player: @players[0] %></li>
<li><%= image_tag('icons8-lamb-64.png', size: '40') %> <%= render "players/player", player: @players[1] %></li>
<li><%= image_tag('icons8-snake-64.png', size: '40') %> <%= render "players/player", player: @players[2] %></li>
<li><%= image_tag('icons8-female-lion-64.png', size: '40') %> <%= render "players/player", player: @players[3] %></li>
</ul>
<%= link_to "update", method: :update, data: {position: params[:position], money: params[:money], remote: true} %>